import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDatabase1773656916722 implements MigrationInterface {
    name = 'InitDatabase1773656916722'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "product_enum_attribute_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "attribute_id" uuid NOT NULL, "value" character varying(255) NOT NULL, "image_url" character varying(500), "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_eeec7d4878ad74ab81eafde97cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_type_config_attributes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_type_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "data_type" character varying(20) NOT NULL, "is_required" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', "validation_rules" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1552b1e62d939e6a30fb626c0a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6ad7b08e6491a02ebc9ed82019d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_statuses" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, CONSTRAINT "UQ_9a42830a21aa98283f6eba807aa" UNIQUE ("name"), CONSTRAINT "PK_d82b6ccd4f16a294aa02b285703" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_attribute_values" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "attribute_id" uuid NOT NULL, "value_string" character varying(500), "value_number" numeric(12,4), "value_boolean" boolean, "value_date" date, "value_enum_option_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d2e88c5209783f87f0881d6dce4" UNIQUE ("product_id", "attribute_id"), CONSTRAINT "PK_b124baf1272037deac1c21cffe1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_quantity_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "unit_name" character varying(50) NOT NULL, "is_base_unit" boolean NOT NULL DEFAULT false, "conversion_factor" numeric(10,4) NOT NULL DEFAULT '1', "is_integer_only" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab1ea8254dcf055c6276b158efa" UNIQUE ("product_id", "unit_name"), CONSTRAINT "PK_340686caf21f44ed47350b16b57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "image_url" character varying(500) NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "is_primary" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "frame_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "frame_style" character varying(50), "rim_type" character varying(20), "frame_width" numeric(5,1), "lens_width" numeric(5,1), "bridge_width" numeric(5,1), "temple_length" numeric(5,1), "frame_color" character varying(50), "gender_target" character varying(10), CONSTRAINT "UQ_51b17edfd07426d84938c2541c2" UNIQUE ("product_id"), CONSTRAINT "REL_51b17edfd07426d84938c2541c" UNIQUE ("product_id"), CONSTRAINT "PK_e9aa4d528e8da0ba2becf0d0b33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lens_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "lens_type" character varying(20), "lens_index" numeric(3,2), "lens_material" character varying(50), "sph" numeric(5,2), "cyl" numeric(5,2), "add_power" numeric(5,2), "diameter" integer, "coating" character varying(100), "is_photochromic" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_f5d870d0236ba8064189d879be4" UNIQUE ("product_id"), CONSTRAINT "REL_f5d870d0236ba8064189d879be" UNIQUE ("product_id"), CONSTRAINT "PK_67fbc7e60cac9a95bbbbf7c73c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c6a3511829cc6908c911067f6a" ON "lens_details" ("sph") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ed91d6c4423619dd86054d9b5" ON "lens_details" ("cyl") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "image_url" character varying(500), "product_type_id" uuid NOT NULL, "status_id" integer NOT NULL DEFAULT '2', "listed_price" numeric(12,2) NOT NULL, "minimum_price" numeric(12,2) NOT NULL, "price_after_tax" boolean NOT NULL DEFAULT true, "is_expirable" boolean NOT NULL DEFAULT false, "min_order_range_count" integer NOT NULL DEFAULT '1', "minimum_saleable_range_count" integer, "meta_data" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7cfc24d6c24f0ec91294003d6b" ON "products" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_9adb63f24f86528856373f0ab9" ON "products" ("product_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fadfdf0a24e9dc5b8d5b85f4ee" ON "products" ("status_id") `);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(50) NOT NULL, "password_hash" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20), "full_name" character varying(255) NOT NULL, "dob" date, "gender" character varying(10), "address" text, "avatar_url" character varying(500), "role" character varying(30) NOT NULL DEFAULT 'customer', "is_verified" boolean NOT NULL DEFAULT false, "last_login_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_477e3187cedfb5a3ac121e899c9" UNIQUE ("username"), CONSTRAINT "UQ_ee66de6cdc53993296d1ceb8aa0" UNIQUE ("email"), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_477e3187cedfb5a3ac121e899c" ON "accounts" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ee66de6cdc53993296d1ceb8aa" ON "accounts" ("email") `);
        await queryRunner.query(`CREATE TABLE "order_statuses" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, CONSTRAINT "UQ_59aa93a6953b828b98972f47661" UNIQUE ("name"), CONSTRAINT "PK_76c6dc5bccb3ef1a4a8510cab3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_methods" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_a793d7354d7c3aaf76347ee5a66" UNIQUE ("name"), CONSTRAINT "PK_34f9b8c6dfb4ac3559f7e2820d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vat_configs" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "value" numeric(5,2) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e8aa30bb2ce3545a3e3356b0d21" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_code" character varying(30) NOT NULL, "customer_id" uuid, "customer_name" character varying(255), "customer_phone" character varying(20), "customer_email" character varying(255), "shipping_address" text, "status_id" integer NOT NULL DEFAULT '1', "payment_method_id" integer, "vat_config_id" integer, "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "discount_amount" numeric(12,2) NOT NULL DEFAULT '0', "vat_amount" numeric(12,2) NOT NULL DEFAULT '0', "total" numeric(12,2) NOT NULL DEFAULT '0', "paid_amount" numeric(12,2) NOT NULL DEFAULT '0', "remaining_amount" numeric(12,2) NOT NULL DEFAULT '0', "notes" text, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e462c2f2237b3049aa6be3fce06" UNIQUE ("order_code"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e462c2f2237b3049aa6be3fce0" ON "orders" ("order_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_772d0ce0473ac2ccfa26060dbe" ON "orders" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_03a801095cb90cf148e474cfcb" ON "orders" ("status_id") `);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "contact_person" character varying(255), "email" character varying(255), "phone" character varying(20), "address" text, "tax_code" character varying(50), "notes" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipment_statuses" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, CONSTRAINT "UQ_254c2f000fe3d8bdf86c5d3ddac" UNIQUE ("name"), CONSTRAINT "PK_acbb0f530b151493f4c9f5bd5ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid, "shipment_status_id" integer NOT NULL DEFAULT '1', "tracking_number" SERIAL NOT NULL, "ordered_at" date, "expected_at" date, "received_at" date, "total_cost" numeric(12,2) NOT NULL DEFAULT '0', "notes" text, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cff64f6f3e15d4fecbdaaa27b" ON "shipments" ("shipment_status_id") `);
        await queryRunner.query(`CREATE TABLE "shipment_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "shipment_id" uuid NOT NULL, "quantity_config_id" uuid NOT NULL, "input_amount" numeric(10,2) NOT NULL, "reserved_count" numeric(10,2) NOT NULL DEFAULT '0', "sold_count" numeric(10,2) NOT NULL DEFAULT '0', "buy_price" numeric(12,2) NOT NULL, "expire_date" date, "manufacture_date" date, "warehouse_location" character varying(50), "is_expired" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7dfc873be1417190f0e5e001dd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5ba11395b33f7e23c6ff29363b" ON "shipment_items" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccc68015ca35631ff542230b20" ON "shipment_items" ("shipment_id") `);
        await queryRunner.query(`CREATE TABLE "order_item_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_item_id" uuid NOT NULL, "shipment_item_id" uuid NOT NULL, "allocated_quantity" numeric(10,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2f6eeb4462b69b8c7a8d5d14327" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_15b37a62dd927b7a10915d32f2" ON "order_item_allocations" ("order_item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3cf1b5de38d3b1e0bf795ecb94" ON "order_item_allocations" ("shipment_item_id") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity_config_id" uuid NOT NULL, "quantity" numeric(10,2) NOT NULL, "unit_price" numeric(12,2) NOT NULL, "discount_amount" numeric(12,2) NOT NULL DEFAULT '0', "line_total" numeric(12,2) NOT NULL, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "warranty_claim_statuses" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, CONSTRAINT "UQ_7fdb1e7fb268b68ef3e51b259dd" UNIQUE ("name"), CONSTRAINT "PK_06c1a3d41063494bffe17910dec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "warranty_claims" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warranty_id" uuid NOT NULL, "issue_description" text NOT NULL, "resolution" text, "status_id" integer NOT NULL DEFAULT '1', "resolved_at" date, "handled_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_10984f957c4bc90ec2b9170214e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_474c79f691d756e613c73a353b" ON "warranty_claims" ("warranty_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd989bf0455f1bbf62d093fd3f" ON "warranty_claims" ("status_id") `);
        await queryRunner.query(`CREATE TABLE "warranties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warranty_code" character varying(30) NOT NULL, "product_id" uuid NOT NULL, "order_item_id" uuid, "customer_id" uuid, "start_date" date NOT NULL, "end_date" date NOT NULL, "duration_months" integer NOT NULL, "terms" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2a8c7bb70be2d72e87f22cd2ab5" UNIQUE ("warranty_code"), CONSTRAINT "PK_62c441630f8a6ddcc4bc1ab1bc5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2a8c7bb70be2d72e87f22cd2ab" ON "warranties" ("warranty_code") `);
        await queryRunner.query(`ALTER TABLE "product_enum_attribute_options" ADD CONSTRAINT "FK_c9ac3692cb9addd012e5e124217" FOREIGN KEY ("attribute_id") REFERENCES "product_type_config_attributes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_type_config_attributes" ADD CONSTRAINT "FK_9c14e78d55a3b0eb7293cfbf12d" FOREIGN KEY ("product_type_id") REFERENCES "product_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" ADD CONSTRAINT "FK_61655fe2f6d179eced519392ced" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" ADD CONSTRAINT "FK_f1f04534a41f575a6def0710063" FOREIGN KEY ("attribute_id") REFERENCES "product_type_config_attributes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" ADD CONSTRAINT "FK_a598446e332f73c843019900021" FOREIGN KEY ("value_enum_option_id") REFERENCES "product_enum_attribute_options"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_quantity_configs" ADD CONSTRAINT "FK_2e2bc73c16458c3a973020afa08" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "frame_details" ADD CONSTRAINT "FK_51b17edfd07426d84938c2541c2" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lens_details" ADD CONSTRAINT "FK_f5d870d0236ba8064189d879be4" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9adb63f24f86528856373f0ab9a" FOREIGN KEY ("product_type_id") REFERENCES "product_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_fadfdf0a24e9dc5b8d5b85f4ee8" FOREIGN KEY ("status_id") REFERENCES "product_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_03a801095cb90cf148e474cfcb7" FOREIGN KEY ("status_id") REFERENCES "order_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_7819f136440d4ae83b20f0267a9" FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_aac45147789d90afa94bf01071e" FOREIGN KEY ("vat_config_id") REFERENCES "vat_configs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_574a2f0932043d4e4baf188ee05" FOREIGN KEY ("created_by") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_4e638602ea498c95d2e4f2bc109" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_2cff64f6f3e15d4fecbdaaa27b8" FOREIGN KEY ("shipment_status_id") REFERENCES "shipment_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_111f29a3517f16391665bf47ac0" FOREIGN KEY ("created_by") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_items" ADD CONSTRAINT "FK_5ba11395b33f7e23c6ff29363b0" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_items" ADD CONSTRAINT "FK_ccc68015ca35631ff542230b209" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_items" ADD CONSTRAINT "FK_c43d64449463ad400e339724b09" FOREIGN KEY ("quantity_config_id") REFERENCES "product_quantity_configs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_allocations" ADD CONSTRAINT "FK_15b37a62dd927b7a10915d32f2d" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_allocations" ADD CONSTRAINT "FK_3cf1b5de38d3b1e0bf795ecb943" FOREIGN KEY ("shipment_item_id") REFERENCES "shipment_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_ec68e95b90a3e09777dd62363d4" FOREIGN KEY ("quantity_config_id") REFERENCES "product_quantity_configs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warranty_claims" ADD CONSTRAINT "FK_474c79f691d756e613c73a353b2" FOREIGN KEY ("warranty_id") REFERENCES "warranties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warranty_claims" ADD CONSTRAINT "FK_fd989bf0455f1bbf62d093fd3fe" FOREIGN KEY ("status_id") REFERENCES "warranty_claim_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warranty_claims" ADD CONSTRAINT "FK_d8acdce7508df97f388df354e67" FOREIGN KEY ("handled_by") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warranties" ADD CONSTRAINT "FK_94f96552f452950801e028e82ab" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warranties" ADD CONSTRAINT "FK_8982e9428f17f25b38e3917a7de" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warranties" ADD CONSTRAINT "FK_c0169557396ca7bab0658bb4d7a" FOREIGN KEY ("customer_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "warranties" DROP CONSTRAINT "FK_c0169557396ca7bab0658bb4d7a"`);
        await queryRunner.query(`ALTER TABLE "warranties" DROP CONSTRAINT "FK_8982e9428f17f25b38e3917a7de"`);
        await queryRunner.query(`ALTER TABLE "warranties" DROP CONSTRAINT "FK_94f96552f452950801e028e82ab"`);
        await queryRunner.query(`ALTER TABLE "warranty_claims" DROP CONSTRAINT "FK_d8acdce7508df97f388df354e67"`);
        await queryRunner.query(`ALTER TABLE "warranty_claims" DROP CONSTRAINT "FK_fd989bf0455f1bbf62d093fd3fe"`);
        await queryRunner.query(`ALTER TABLE "warranty_claims" DROP CONSTRAINT "FK_474c79f691d756e613c73a353b2"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_ec68e95b90a3e09777dd62363d4"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "order_item_allocations" DROP CONSTRAINT "FK_3cf1b5de38d3b1e0bf795ecb943"`);
        await queryRunner.query(`ALTER TABLE "order_item_allocations" DROP CONSTRAINT "FK_15b37a62dd927b7a10915d32f2d"`);
        await queryRunner.query(`ALTER TABLE "shipment_items" DROP CONSTRAINT "FK_c43d64449463ad400e339724b09"`);
        await queryRunner.query(`ALTER TABLE "shipment_items" DROP CONSTRAINT "FK_ccc68015ca35631ff542230b209"`);
        await queryRunner.query(`ALTER TABLE "shipment_items" DROP CONSTRAINT "FK_5ba11395b33f7e23c6ff29363b0"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_111f29a3517f16391665bf47ac0"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_2cff64f6f3e15d4fecbdaaa27b8"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_4e638602ea498c95d2e4f2bc109"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_574a2f0932043d4e4baf188ee05"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_aac45147789d90afa94bf01071e"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_7819f136440d4ae83b20f0267a9"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_03a801095cb90cf148e474cfcb7"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_fadfdf0a24e9dc5b8d5b85f4ee8"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9adb63f24f86528856373f0ab9a"`);
        await queryRunner.query(`ALTER TABLE "lens_details" DROP CONSTRAINT "FK_f5d870d0236ba8064189d879be4"`);
        await queryRunner.query(`ALTER TABLE "frame_details" DROP CONSTRAINT "FK_51b17edfd07426d84938c2541c2"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "product_quantity_configs" DROP CONSTRAINT "FK_2e2bc73c16458c3a973020afa08"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" DROP CONSTRAINT "FK_a598446e332f73c843019900021"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" DROP CONSTRAINT "FK_f1f04534a41f575a6def0710063"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" DROP CONSTRAINT "FK_61655fe2f6d179eced519392ced"`);
        await queryRunner.query(`ALTER TABLE "product_type_config_attributes" DROP CONSTRAINT "FK_9c14e78d55a3b0eb7293cfbf12d"`);
        await queryRunner.query(`ALTER TABLE "product_enum_attribute_options" DROP CONSTRAINT "FK_c9ac3692cb9addd012e5e124217"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a8c7bb70be2d72e87f22cd2ab"`);
        await queryRunner.query(`DROP TABLE "warranties"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd989bf0455f1bbf62d093fd3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_474c79f691d756e613c73a353b"`);
        await queryRunner.query(`DROP TABLE "warranty_claims"`);
        await queryRunner.query(`DROP TABLE "warranty_claim_statuses"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3cf1b5de38d3b1e0bf795ecb94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15b37a62dd927b7a10915d32f2"`);
        await queryRunner.query(`DROP TABLE "order_item_allocations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccc68015ca35631ff542230b20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ba11395b33f7e23c6ff29363b"`);
        await queryRunner.query(`DROP TABLE "shipment_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cff64f6f3e15d4fecbdaaa27b"`);
        await queryRunner.query(`DROP TABLE "shipments"`);
        await queryRunner.query(`DROP TABLE "shipment_statuses"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03a801095cb90cf148e474cfcb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_772d0ce0473ac2ccfa26060dbe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e462c2f2237b3049aa6be3fce0"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TABLE "vat_configs"`);
        await queryRunner.query(`DROP TABLE "payment_methods"`);
        await queryRunner.query(`DROP TABLE "order_statuses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee66de6cdc53993296d1ceb8aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_477e3187cedfb5a3ac121e899c"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fadfdf0a24e9dc5b8d5b85f4ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9adb63f24f86528856373f0ab9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cfc24d6c24f0ec91294003d6b"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ed91d6c4423619dd86054d9b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6a3511829cc6908c911067f6a"`);
        await queryRunner.query(`DROP TABLE "lens_details"`);
        await queryRunner.query(`DROP TABLE "frame_details"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP TABLE "product_quantity_configs"`);
        await queryRunner.query(`DROP TABLE "product_attribute_values"`);
        await queryRunner.query(`DROP TABLE "product_statuses"`);
        await queryRunner.query(`DROP TABLE "product_types"`);
        await queryRunner.query(`DROP TABLE "product_type_config_attributes"`);
        await queryRunner.query(`DROP TABLE "product_enum_attribute_options"`);
    }

}
